### ISSUE TITLE
Small typo in 'Ganga persistance storage task' section

### ISSUE THREAD

**Issue by varunbankar** [ganga-devs/GangaGSoC2024#1]
A small typo I noticed while reading the challenge, I thought I would point it out :)

<img width="921" alt="Screenshot 2020-02-26 at 6 23 57 PM" src="https://user-images.githubusercontent.com/47035057/75346707-4bb24f80-58c5-11ea-8c09-fe64ee734222.png">

In the last line, there is a small typo in the word `Make` & `to the`.

**Comment by egede** [comment]
Fixed. Many thanks.
